BOOTSTRAP_SERVER: 192.168.29.247:9092
KAFKA_MAX_POLL_RECORD: 1000
KAFKA_CONSUMER_GROUP_ID: booking-consumer-test
KAFKA_BOOKING_SERVICE_TOPIC_NAME: booking_topic
KAFKA_INVOICE_SERVICE_TOPIC_NAME: invoice_topic
KAFKA_CAMEL_TOPIC_NAME: apache_camel_topic


camel:
  servlet:
    mapping:
      context-path: /services/*
  springboot:
    main-run-controller: true

server:
  port: 9090
app:
  camel-from: 'kafka:${KAFKA_CAMEL_TOPIC_NAME}?brokers=${BOOTSTRAP_SERVER}&maxPollRecords=${KAFKA_MAX_POLL_RECORD}&groupId=${KAFKA_CONSUMER_GROUP_ID}'
  camel-to-booking-service: 'kafka:${KAFKA_BOOKING_SERVICE_TOPIC_NAME}?brokers=${BOOTSTRAP_SERVER}'
  camel-to-invoice-service: 'kafka:${KAFKA_INVOICE_SERVICE_TOPIC_NAME}?brokers=${BOOTSTRAP_SERVER}'



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      group:
        liveness:
          include: diskSpace,ping
          show-details: always
      probes:
        enabled: true
logging:
  level:
    org.springframework: INFO
    org.apache.camel.spring.boot: INFO
    org.apache.camel.health: DEBUG
    org.apache.camel.impl.health: DEBUG
    sample.camel: DEBUG